### ISSUE TITLE
Core addons going to vendor/anomaly/* instead of core/anomaly/*

### ISSUE THREAD

**Issue by liviumalvin** [anomalylabs/streams-composer-plugin#1]
`getPackageBasePath -> getInstallPath`

I literally cannot understand the exact reason, but apparently the `getPackageBasePath` in AddonInstaller.php file does not get called by the installer. Switching the method name to `getInstallPath` will do the trick.

**Comment by RyanThompson** [comment]
Fixed - https://github.com/anomalylabs/streams-composer-plugin/pull/2
