### ISSUE TITLE
Problem with composer install

### ISSUE THREAD

**Issue by 007lock** [anomalylabs/streams-composer-plugin#3]
When i composer install this thing happen. Please help me to fix it.

The "anomaly/streams-composer-plugin" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).

**Comment by RyanThompson** [comment]
That's just a waring that will be addressed this week. No actual issue / error.

**Comment by 007lock** [comment]
@RyanThompson thank for your answer.
